- hosts: localhost
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - name: Include git setup tasks
      include_tasks: tasks/git-setup.yml

    - name: Include core setup tasks
      include_tasks: tasks/core-setup.yml

    - name: Include node setup tasks
      include_tasks: tasks/node-setup.yml

    - name: Include npm packages setup
      include_tasks: tasks/npm-packages.yml

    - name: Include zsh setup
      include_tasks: tasks/zsh-setup.yml

    - name: Include nvim setup
      include_tasks: tasks/nvim-setup.yml

    - name: Include productivity tools setup
      include_tasks: tasks/productivity-tools.yml
