- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    name: ['build-essential', 'cmake', 'pkg-config', 'libpthread-stubs0-dev']
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, gettext)
  become: true
  apt:
    name: ['lua5.1', 'unzip', 'gettext']
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name:
      [
        'compton',
        'curl',
        'htop',
        'golang',
        'lsof',
        'i3',
        'ccache',
        'ninja-build',
        'python3-pip',
        'nvidia-settings',
        'pavucontrol',
        'moreutils',
        'clangd',
      ]
  tags:
    - install
    - core
