- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "the.primeagen@gmail.com"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "ThePrimeagen"
  tags:
  - git-personal
- name: Git Rustin
  git_config:
    name: user.email
    scope: global
    value: "rustin.deeznuts@gmail.com"
  tags:
  - git-rustin
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "RustLover69"
  tags:
  - git-rustin
- name: Netflix
  git_config:
    name: user.email
    scope: global
    value: "mpaulson@netflix.com"
  tags:
  - git-netflix
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "mpaulson"
  tags:
  - git-netflix
